export const testConfig = {
    WFM:'https://primark-uat.npr.mykronos.com/wfd/home',
    qa: `https://demoqa.com`,
    dev: ``,
    qaApi: `https://reqres.in`,
    devApi: ``,
    username: `demouat@gmail.com`,
    password: `U2FsdGVkX18/eMdsOJpvI4hJZ/w7hNgwSRFaDvAcZx4=`,
    WFMUSername: `10649030`,
    WFMPassword:'U2FsdGVkX18V5h3fyN7305Rg+oaJ6z76An0VSo6P62HeiqwLsRXOxlRANt5fWQ3g',
    WFMEmpUSername: `10649086`,
    WFMEmpPassword:'WFMManagerPassword@05!',
   //WFMMgrUSername: `10648949`,
   WFMMgrUSername: `10648831`,
    WFMMgrPassword: 'WFMManagerPassword@06',
    WFMUsrUsername: 'vezhil@primark.ie',
    WFMUsrPassword: 'NewpasswordMicrosoft@14',
    
    waitForElement: 60,
    dbUsername: ``,
    dbPassword: ``,
    dbServerName: ``,
    dbPort: ``,
    dbName: ``
}